"""empty message

Revision ID: 44d9f8e82408
Revises: 
Create Date: 2023-02-16 14:54:51.633168

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44d9f8e82408'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(length=150), nullable=True),
    sa.Column('last_name', sa.String(length=150), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('g_auth_verify', sa.Boolean(), nullable=True),
    sa.Column('token', sa.String(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('character',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('race', sa.String(length=100), nullable=True),
    sa.Column('background', sa.String(length=150), nullable=True),
    sa.Column('inventory', sa.String(), nullable=True),
    sa.Column('token', sa.String(), nullable=True),
    sa.Column('player_token', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['player_token'], ['player.token'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('inventory'),
    sa.UniqueConstraint('token')
    )
    op.create_table('inventory',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('character_token', sa.String(), nullable=False),
    sa.Column('max_carry', sa.String(length=5), nullable=True),
    sa.Column('current_carry', sa.String(length=5), nullable=True),
    sa.Column('bag', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['character_token'], ['character.token'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inventory')
    op.drop_table('character')
    op.drop_table('player')
    # ### end Alembic commands ###
